version: '3'
services:
   db_container:
      build: ./E4
      command: --default-authentication-plugin=mysql_native_password
   web:
      build: ./E2
      depends_on:
      - db_container
      ports:
      - 7000:80

