apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment-antje12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-pod-antje12
  template:
    metadata:
      labels:
        app: webserver-pod-antje12
    spec:
      containers:
        - name: webserver-antje12
          image: antje12/l2e2image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service-antje12
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30724
  selector:
    app: webserver-pod-antje12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-antje12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod-antje12
  template:
    metadata:
      labels:
        app: mysql-pod-antje12
    spec:
      containers:
        - name: mysql
          image: antje12/l2e4image
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
---
  apiVersion: v1
  kind: Service
  metadata:
    name: antje12service
  spec:
    ports:
      - port: 3306
        targetPort: 3306
    selector:
      app: mysql-pod-antje12