apiVersion: v1
kind: Service
metadata:
  name: webserver-service-maha618
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30723
  selector:
    app: webserver-pod-maha618
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment-maha618
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-pod-maha618
  template:
    metadata:
      labels:
        app: webserver-pod-maha618
    spec:
      containers:
        - name: webserver-maha618
          image: xmimmer/l2e2
          ports:
            - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: maha618service
  spec:
    ports:
      - port: 3306
        targetPort: 3306
    selector:
      app: mysql-pod-maha618
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-maha618
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod-maha618
  template:
    metadata:
      labels:
        app: mysql-pod-maha618
    spec:
      containers:
        - name: mysql
          image: xmimmer/l2e4
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306