version: '3.5'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/config/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certificates/rootCA.pem:/etc/nginx/ssl/rootCA.pem
      - ./proxy/certificates/site.crt:/etc/nginx/ssl/site.crt
      - ./proxy/certificates/site.key:/etc/nginx/ssl/site.key
    networks:
      - frontend
    depends_on:
      - backend

  backend:
    build: ./backend
#    ports:
#      - 5000:5000
    networks:
      - frontend
      - backend
    depends_on:
      - database
  database:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

networks:
  frontend:
  backend:
  